name: Main

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+.rc[0-9]+'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@main
    with:
      CMAKE_SE_BUILD_PRESET: 'vs2022-windows-vcpkg-se'
      CMAKE_AE_BUILD_PRESET: 'vs2022-windows-vcpkg-ae'
      CMAKE_VR_CONFIG_PRESET: ''
      CMAKE_VR_BUILD_PRESET: ''
      FOMOD_INCLUDE_PDB: true
      FOMOD_MOD_NAME: "NPCs Learn to Barter"
      FOMOD_MOD_AUTHOR: "sasnikol"
      FOMOD_MOD_NEXUS_ID: "120558"
      FOMOD_DEFAULT_IMAGE: "FOMOD/images/cover.png"
      VCPKG_COMMIT_ID: '06475a351672e6fad52e707b33e30eaf2811d341'